group: edge
dist: trusty
language: node_js
node_js: 6
cache:
  directories:
    - node_modules
install:
  - true
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm i
  - npm test
#  - npm run e2e
  - npm run dev
  - npm run build
notifications:
  on_failure: change # always
  on_success: never
